spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/stock
    username: stock
    password: stock
    driverClassName: org.postgresql.Driver

# spring:
#   jpa:
#     database: POSTGRESQL
#     show-sql: true
#     hibernate:
#       ddl-auto: create-drop
#   datasource:
#     platform: postgres
#     url: jdbc:postgresql://localhost:5432/stock
#     username: stock
#     password: stock
#     driverClassName: org.postgresql.Driver
server:
  port: 8099

# spring:
#   datasource:
#     url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:stock}
#     username: ${POSTGRES_USERNAME:stock}
#     password: ${POSTGRES_PASSWORD:stock}
